### ISSUE TITLE
Update header và product-detail

### ISSUE THREAD

**Issue by tranvulamdev88** [huynhvanhuuan/Project-Web-Development-NLU#6]
Mọi người vào check lại product-detail nhé. Mình vừa update header và thêm 1 số phần cho product-detail.
Phần đặt biến mình cũng đã đặt xong rồi mọi người vô nhận xét.

**Comment by huynhvanhuuan** [comment]
Cái header logo của ông là Amanda phải không Lam?

**Comment by tranvulamdev88** [comment]
Tui lấy đại 1 hình trên google về thôi á

**Comment by tranvulamdev88** [comment]
Amanda
